// Two tiers of dictionary, both generated by scripts/build-words.mjs:
//  - VALID:  every 4-letter word the player may submit. Also the graph the
//            pathfinder searches, so "optimal" means optimal over what is allowed.
//  - COMMON: everyday words. Starting words are drawn only from here so a
//            puzzle never opens on obscure Scrabble fodder.
import { VALID, COMMON } from './dictionary.js'

export const TARGET = 'TURD'

function parse(text) {
  return Array.from(
    new Set(
      text
        .split(/\s+/)
        .map((w) => w.trim().toUpperCase())
        .filter((w) => /^[A-Z]{4}$/.test(w)),
    ),
  )
}

export const WORDS = parse(VALID)
export const WORD_SET = new Set(WORDS)

export const COMMON_WORDS = parse(COMMON).filter((w) => WORD_SET.has(w))
export const COMMON_SET = new Set(COMMON_WORDS)

export function isValidWord(word) {
  return WORD_SET.has(String(word).toUpperCase())
}
