/**
 * Regenerates src/game/dictionary.js from public-domain word lists.
 *
 *   node scripts/build-words.mjs
 *
 * The output is committed, so the game itself never touches the network.
 *
 * Sources:
 *  - ENABLE (public domain, the Scrabble-style list many word games use):
 *    every 4-letter word becomes a VALID word for moves and for pathfinding.
 *  - Google 10k most common English words: the 4-letter ones that are also
 *    in ENABLE become the COMMON pool that starting words are drawn from,
 *    so a puzzle never starts on something nobody has heard of.
 */
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const ENABLE_URL = 'https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt'
const COMMON_URL =
  'https://raw.githubusercontent.com/first20hours/google-10000-english/master/google-10000-english-usa.txt'

// Words we always want available even if a source list lacks them.
const EXTRA_VALID = ['TURD']
// Words that must never be a STARTING word. They remain valid moves.
// Toilet humour is the whole point of the game, so SHIT, CRAP, PISS and friends
// stay in. Sexual, violent and slur-adjacent words are kept off the opening tile.
const NEVER_START = new Set([
  'ANAL', 'BOOB', 'COCK', 'CUNT', 'DICK', 'FUCK', 'GAYS', 'JEWS', 'NUDE',
  'ORGY', 'PORN', 'RAPE', 'SEXY', 'SLUT', 'TITS',
])

async function fetchWords(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${url}: ${res.status}`)
  const text = await res.text()
  return text
    .split(/\r?\n/)
    .map((w) => w.trim().toUpperCase())
    .filter((w) => /^[A-Z]{4}$/.test(w))
}

const enable = new Set([...(await fetchWords(ENABLE_URL)), ...EXTRA_VALID])
const googleCommon = await fetchWords(COMMON_URL)

const valid = [...enable].sort()
const common = [...new Set(googleCommon)]
  .filter((w) => enable.has(w) && !NEVER_START.has(w))
  .sort()

const out = `// GENERATED by scripts/build-words.mjs. Do not edit by hand.
// ${valid.length} valid 4-letter words (ENABLE), ${common.length} common ones (Google 10k ∩ ENABLE).

export const VALID = \`
${chunk(valid)}
\`

export const COMMON = \`
${chunk(common)}
\`
`

const target = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src/game/dictionary.js')
await writeFile(target, out)
console.log(`wrote ${target}: ${valid.length} valid, ${common.length} common`)

function chunk(words, perLine = 16) {
  const lines = []
  for (let i = 0; i < words.length; i += perLine) lines.push(words.slice(i, i + perLine).join(' '))
  return lines.join('\n')
}
